name: Build iOS Application
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Dependencies
        run: npm install

      - name: Add iOS Platform
        run: cordova platform add ios

      - name: Build iOS Simulator App
        run: cordova build ios --emulator --nobuild
